version: '3.8'

services:
  flask-app:
    build: ./flask-app
    ports:
      - "5000:5000"
    environment:
      - FLASK_SECRET_KEY=your-secret-key-change-me
      - OIDC_DISCOVERY_URL=http://dex:5556/dex/.well-known/openid-configuration
      - OIDC_CLIENT_ID=flask-app
      - OIDC_CLIENT_SECRET=flask-app-secret
      - OIDC_REDIRECT_URI=http://localhost:5000/callback
    depends_on:
      - dex
    networks:
      - auth-network

  dex:
      image: ghcr.io/dexidp/dex:v2.37.0
      volumes:
        - ./dex/config.yaml:/etc/dex/config.yaml
      ports:
        - "5556:5556"
      depends_on:
        keycloak:
          condition: service_started
      networks:
        - auth-network
      command: ["/bin/sh", "-c", "sleep 60 && dex serve /etc/dex/config.yaml"] #ajout de sleep
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:5556/health"]
        interval: 10s
        timeout: 5s
        retries: 3 

  keycloak:
    image: keycloak/keycloak:26.1.5
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_FEATURES=admin-fine-grained-authz
      - KC_HEALTH_ENABLED=true
    volumes:
      - ./keycloak/imports:/opt/keycloak/data/import
    command:
      - start-dev
      - --import-realm
      - --verbose
    networks:
      - auth-network

networks:
  auth-network:
    driver: bridge 