connectors:
- config:
    claimMapping:
      email: email
      groups: groups
      name: name
      username: preferred_username
    clientID: dex
    clientSecret: jgpS5zbQfZsGRYvIaqQ532RjrQUzKGFJ
    insecureSkipVerify: true
    issuer: http://keycloak:8080/realms/KC_AAS
    redirectURI: http://dex:5556/callback
  id: keycloak
  name: Keycloak
  type: oidc
enablePasswordDB: false
issuer: http://dex:5556
logger:
  format: text
  level: debug
oauth2:
  responseTypes:
  - code
  - token
  - id_token
  skipApprovalScreen: true
staticClients:
- id: flask-app
  name: Flask App
  redirectURIs:
  - http://localhost:5000/callback
  secret: flask-app-secret
storage:
  type: memory
web:
  http: 0.0.0.0:5556
